### ISSUE TITLE
doors doesn’t work on coraptions

### ISSUE THREAD

**Issue by BlahajTheShark14** [ValkyrienSkies/Create-Interactive-Issues#112]
e.g.: like on an elevator, or on a train. Idk why is this mod abandoned. If the bigger issues would be fixed, it would became a great mod!

**Comment by xiewuzhiying** [comment]
Fixed in development version

**Comment by BlahajTheShark14** [comment]
oh thats cool, when it will came out? (approx)

**Comment by BlahajTheShark14** [comment]
like, it will be ready in this month?

**Comment by blockninja124** [comment]
Closing as I think this is a duplicate of https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/97. As to when the update will come out, I don’t know. Chances are it’ll be within a month or so?
