### ISSUE TITLE
Compatibility error with Create Steam 'n' Rails

### ISSUE THREAD

**Issue by azur84** [ValkyrienSkies/Create-Interactive-Issues#22]
Hello
The block railway:track_coupler of Create Steam 'n' Rails (Steam_Rails-1.4.8+forge-mc1.18.2-build.23.jar) does not work with Interactive (create_interactive-118-forge-1.0.0-beta.1ef6fb0b989.jar)
![2023-12-26_13 31 45](https://github.com/ValkyrienSkies/Create-Interactive-Issues/assets/119055182/6e5e3726-00a5-4eb4-8a51-297812fd3b20)
Thank you.

**Comment by ThePlasticPotato** [comment]
Can you elaborate on the issue?

**Comment by azur84** [comment]
This block should link the trains together with a redstone circuit but with Interactive the block does nothing

**Comment by Chump-the-Lump** [comment]
It worked for me, i think you need to moved them closer togeather

**Comment by azur84** [comment]
ok thank you

**Comment by stacode123** [comment]
Please close issue as it is not a Create Interactive issue and clutters the issue tab :)
