### ISSUE TITLE
Behavior conflict with drills and deployers on trains

### ISSUE THREAD

**Issue by Chump-the-Lump** [ValkyrienSkies/Create-Interactive-Issues#24]
Drills and deployers still power themselves on a moving train. This causes problems when trying to use deployers to make a precision meconium as it places down cogs instead of using them.

**Comment by StewStrong** [comment]
In the latest interactive we added a way to disable this behavior on deployers. Its not on curse yet, but you can get it from our website https://www.valkyrienskies.org/interactive
