### ISSUE TITLE
OptiFine 1.18.2 HD U H9 + Create: Interactive = missing trainblocks

### ISSUE THREAD

**Issue by JavaBoii** [ValkyrienSkies/Create-Interactive-Issues#25]
Issue:

If the game is running OptiFine and you want to build a train with Create: Interactive installed. All blocks present and placed onto the assembled train disappear. The Train still functions, you can build and brake blocks on it. You can build moving contraptions on it.
The only thing missing is all the block textures [ as seen in picture ]
After removing all the mods one by one i identified OptiFine to be the problem, which sucks. 

Otherwise thank you very much for this mod. Its amazing.

[image]
![Screenshot 2023-12-29 164743](https://github.com/ValkyrienSkies/Create-Interactive-Issues/assets/79570962/1b4e433e-e9d0-44c0-9354-3f7823245ed3)

Forge Version:

    40.2.9

Mods Used:

    OptiFine_1.18.2_HD_U_H9
    create_interactive-118-forge-1.0.0-beta.1ef6fb0b989
    create-1.18.2-0.5.1.f
    kotlinforforge-3.12.0-all
    valkyrienskies-118-2.1.1-beta.4

**Comment by T0RNATO** [comment]
1. Please never never use Optifine
2. If you insist upon using Optifine, never report issues it causes to other mod developers. Optifine, being a closed source mod cannot really be worked around and the onus is never on mod devs to cater to it.

**Comment by Tyrthurey** [comment]
Use iris or sodium instead
