### ISSUE TITLE
Crash when loading in a deployer on a eureka air ship due to a class definition error

### ISSUE THREAD

**Issue by Chump-the-Lump** [ValkyrienSkies/Create-Interactive-Issues#29]
The game throughs this error when joining a server with this mod and eureka on it. The server dose not crash just the client.

---- Minecraft Crash Report ----
// There are four lights!

Time: 12/30/23, 11:32 AM
Description: Unexpected error

java.lang.AbstractMethodError: Receiver class org.valkyrienskies.create_interactive.aux.?_???_? does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_243 getSouthLocation()' of abstract class com.simibubi.create.foundation.blockEntity.behaviour.ValueBoxTransform$Sided.
	at com.simibubi.create.foundation.blockEntity.behaviour.ValueBoxTransform$Sided.getLocalOffset(ValueBoxTransform.java:104)
	at com.simibubi.create.foundation.blockEntity.behaviour.ValueBoxTransform.testHit(ValueBoxTransform.java:28)
	at com.simibubi.create.foundation.blockEntity.behaviour.ValueBoxTransform$Sided.testHit(ValueBoxTransform.java:128)
	at com.simibubi.create.foundation.blockEntity.behaviour.scrollValue.ScrollValueBehaviour.testHit(ScrollValueBehaviour.java:140)
	at com.simibubi.create.foundation.blockEntity.behaviour.scrollValue.ScrollValueRenderer.tick(ScrollValueRenderer.java:57)
	at com.simibubi.create.foundation.events.ClientEvents.onTick(ClientEvents.java:167)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bhp000$fabric-lifecycle-events-v1$onEndTick(class_310.java:7472)
	at net.minecraft.class_310.method_1574(class_310.java:1817)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.simibubi.create.foundation.blockEntity.behaviour.ValueBoxTransform$Sided.getLocalOffset(ValueBoxTransform.java:104)
	at com.simibubi.create.foundation.blockEntity.behaviour.ValueBoxTransform.testHit(ValueBoxTransform.java:28)
	at com.simibubi.create.foundation.blockEntity.behaviour.ValueBoxTransform$Sided.testHit(ValueBoxTransform.java:128)
	at com.simibubi.create.foundation.blockEntity.behaviour.scrollValue.ScrollValueBehaviour.testHit(ScrollValueBehaviour.java:140)
	at com.simibubi.create.foundation.blockEntity.behaviour.scrollValue.ScrollValueRenderer.tick(ScrollValueRenderer.java:57)
	at com.simibubi.create.foundation.events.ClientEvents.onTick(ClientEvents.java:167)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bhp000$fabric-lifecycle-events-v1$onEndTick(class_310.java:7472)

-- Affected level --
Details:
	All players: 1 total; [class_746['Chump_the_Lump'/6090, l='ClientLevel', x=-346.57, y=77.81, z=1338.54]]
	Chunk stats: 1024, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (256,73,416), Section: (at 0,9,0 in 16,4,26; chunk contains blocks 256,-64,416 to 271,319,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1720568 game time, 2296527 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, border, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1194575280 bytes (1139 MiB) / 2919235584 bytes (2784 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.89
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3770
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28510.81
	Virtual memory used (MB): 19473.80
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 656.71
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 4.11.90
		brrp_v1: Better Runtime Resource Pack (BRRP) v1 1.0.1
		byg: Oh The Biomes You'll Go 1.4
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		create: Create 0.5.1-c-build.1159+mc1.18.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-38
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.4
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.1095-beta+1.18.2
				serialization_hooks: Serialization Hooks 0.3.23
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.11
		create_interactive: Create: Interactive 1.0.0-beta.1
		create_so: Create: Sandpaper Overhaul 1.6+1.18.2
		createaddition: Create Crafts & Additions 20230704a
			team_reborn_energy: Energy 2.2.0
		createbigcannons: Create Big Cannons 0.5.3.a-nightly-42892de
			ritchiesprojectilelib: Ritchie's Projectile Library 1.0.0-3a68f88+1.18.2-fabric
		createchunkloading: Create Chunkloading 1.4.1
		distanthorizons: Distant Horizons 2.0.1-a
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.8+54e5b2ec60
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
		extshape: Extended Block Shapes 2.0.5
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.13+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.7+d7c144a860
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.5.0+bf48649860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.1+03e2b68760
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.12+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.14+b4f4f6cd60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.11+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.13+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		ferritecore: FerriteCore 4.2.1
		indium: Indium 1.0.7+mc1.18.2
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 10.2.1.1002
		lithium: Lithium 0.10.3
		minecraft: Minecraft 1.18.2
		phosphor: Phosphor 0.8.1
		railways: Create: Steam 'n Rails 1.4.4+fabric-mc1.18.2-build.13
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		terrablender: TerraBlender 1.2.0.126
		valkyrienskies: Valkyrien Skies 2 2.1.1-beta.5
			cloth-config: Cloth Config v6 6.3.81
				cloth-basic-math: cloth-basic-math 0.6.1
		vs_eureka: VS Eureka Mod 1.4.0-beta.1
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.15.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.70, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/border (incompatible)
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics

**Comment by StewStrong** [comment]
This should be fixed in beta 2, which is on the website now
