### ISSUE TITLE
a very specific client crash on startup [quilt 1.20.1]

### ISSUE THREAD

**Issue by Kynz0** [ValkyrienSkies/Create-Interactive-Issues#54]
i was making a modpack and after a long time finally figured out what caused a crash on startup:
it was the combination of having the [kiwi ](https://modrinth.com/mod/kiwi)mod and the [SwingThrough ](https://modrinth.com/mod/swingthrough)mod along side interactive (+create and valkyrien skies ofc)

versions: quilt 1.20.1

crash-log:
[crash-2024-01-16_16.06.43-client.txt](https://github.com/ValkyrienSkies/Create-Interactive-Issues/files/13952093/crash-2024-01-16_16.06.43-client.txt)

**Comment by PriestOfFerns** [comment]
Are you sure this is an interactive issue and not a VS2 one? Does the game still crash if you remove Interactive?

**Comment by Kynz0** [comment]
oh my, iam sorry i dont know how i missed that, i would swear that i checked for that. :D
