### ISSUE TITLE
Placing train tracks on rotated contraption does not work as expected

### ISSUE THREAD

**Issue by T0RNATO** [ValkyrienSkies/Create-Interactive-Issues#6]
The rotation of the worldshell upon which the traintracks are placed is not taken into account when determining if a train track placement is valid.

Images:
![image](https://github.com/StewStrong/Create-Interactive-Issues/assets/62496453/9ea14fb9-79c2-4333-97ea-8fb336779128)
![image](https://github.com/StewStrong/Create-Interactive-Issues/assets/62496453/e8e1278d-bae7-42d5-ba95-40a48b022743)

You can see that the player has to be at a strange angle to allow placement.

**Comment by StewStrong** [comment]
This is fixed in the latest version, though it might show up on curse until monday

**Comment by StewStrong** [comment]
You can get the latest version on our website https://www.valkyrienskies.org/interactive
