### ISSUE TITLE
Prism launcher with optifine on 1.20.1 not working.

### ISSUE THREAD

**Issue by Aqua56** [ValkyrienSkies/Create-Interactive-Issues#60]
On prism launcher I open minecraft forge 1.20.1 and it simply exits with code 2.

screen shot](https://github.com/ValkyrienSkies/Create-Interactive-Issues/assets/158493709/6c705f68-a363-476d-b6b4-b8a3059d572e)

**Comment by DerCommander323** [comment]
Don't use Optifine, use alternatives like Embeddium and its addons

**Comment by blockninja124** [comment]
Optifine is incompatible with valkyrien skies. Compat is not planned, use alternatives:
**FORGE**
- embeddium (performance)
- oculus (shaders for embeddium)
**FABRIC**
- sodium (performance)
- Iris shaders (shaders for sodium)
