### ISSUE TITLE
Elevator doors do not open/close

### ISSUE THREAD

**Issue by winnipeg21** [ValkyrienSkies/Create-Interactive-Issues#75]
Using elevators with Create: Interactive works normally. Once I installed the mod elevator doors refuse to open  (when already closed) and refuse to close (when already open). Going to assume this might have some connection with #33 as door controls are connected to the Elevator contact.

**Comment by Constanted313** [comment]
Has there been a solution to this problem? I also tried Create Interative 1.0.3 beta 2 and ValkyrianSkies 2.3.0 beta 5 (Both Fabric). Doors in assembled elevators and trains also become non-interactive blocks. 
When disabling these two mods, the doors become normal again.

**Comment by JeSuisUnCaillou** [comment]
I've got the exact same problem. Doors won't move once the elevator is built.

[The wiki of the sliding door](https://create.fandom.com/wiki/Sliding_Door) says _"Sliding Doors no longer open and close whenever a Contraption stops or starts."_ in 0.5.1 history while at the same time saying _"Sliding Doors will automatically close when a Contraption starts to move."_ in the main description.

So is it supposed to open/close when the contraption moves or not ? 🤔

**Comment by BlahajTheShark14** [comment]
you can open the doors while the coraption is moving, it just automatically closes, when thze coraption starts moving. i installed create: interactive and when i make an elevator, the doors just become solid, non-interactible blocks. if i take out interactive, the doors become normal again. this has to be fixed

**Comment by JeSuisUnCaillou** [comment]
Update : I ended up removing the mod "Create Interactive" and now it works fine.

**Comment by BlahajTheShark14** [comment]
i will do this too, i dont know why the devs dont care about this mod.... it would be a great mod (if they are fix these issues...) i tried to contact with them but i failed.

**Comment by blockninja124** [comment]
Closing as a duplicate of https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/97
