### ISSUE TITLE
Create interactive Fabric Crash while loading word

### ISSUE THREAD

**Issue by unjuannito** [ValkyrienSkies/Create-Interactive-Issues#86]
With the last version of Create Fabric, Create Interactive and Valkiyries skyes the game crash while loading a world
The log:
[latest.log](https://github.com/ValkyrienSkies/Create-Interactive-Issues/files/15365713/latest.log)

**Comment by CheetahCyberBoi** [comment]
Having this too.

**Comment by Kitieshka** [comment]
me too

**Comment by blockninja124** [comment]
This this is a duplicate of https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/89
