### ISSUE TITLE
No fuctionality in 1.20.1 forge.

### ISSUE THREAD

**Issue by Rtificer** [ValkyrienSkies/Create-Interactive-Issues#88]
After launching the game in 1.20.1 forge, with just the required mods; I only used Architectury, Create, Create: Interactive, Kotlin, and Valkyrian skies, and it straight up just doesn't have any functionality. While all the blocks, like the propigator bearing are still there, they do not work. Building on contraptions doesn't work. Upon creating a contraption, like a train, the log is spammed with "Ship with ID 3 has a mass of 0.0, not creating a ShipObject"
[latest.log](https://github.com/user-attachments/files/15597127/latest.log)
Forge Version is the Recommended, 47.3.0

**Comment by spankyyy** [comment]
same here but idk about the error message

**Comment by NinetyUnderScore** [comment]
beta.1 work for me but beta.2 does not. Beta. 1 however is not a solution to my issues since beta. 1 causes moving parts to become invisible until the chunk is updated.

#### Mod list:
kotlinforforge 4.11.0-all
Valkyrien Skies 2 2.3.0-beta.5
Create 0.5.1.f
Create: Copycats+ 1.20.1-1.3.1
Create: Interactive 1.0.2-beta.2

**Comment by NinetyUnderScore** [comment]
Spoke with a developer about it and they said the config must be set to make the default interaction setting for creations to be enabled, however they also said this feature is currently broken so you would have to place the "interact me" block on all creations. I find this to not be worth the effort so with the help of another user on the discord we found a work around to fix this issue temporarily:

1. Downgrade Create:Interactive to Beta.1
2. Install Embeddium 0.3.20+mc1.20.1

**Comment by catreplicators** [comment]
Same issue on Fabric as well.
