### ISSUE TITLE
Create interactive causes all contraptions to have no inventory

### ISSUE THREAD

**Issue by Gray2743** [ValkyrienSkies/Create-Interactive-Issues#91]
Tried to make a automatic rotary crop farm the way all create players know how - with a windmill bearing, harvesters, and a dream. It would simply leave the items on the ground. Found out that I also could not manually access the chest by clicking when it was moving. Same issue for minecart and bearing contraptions. This was not the case before I installed create interactive. Uninstalling interactive fixed the issue immediately.

### Relevant Versions:
Minecraft: 1.20.1
Fabric: 0.15.11
Fabric API: 0.92.2+1.20.1
Create Mod: 0.5.1-f-build.1417+mc1.20.1
Create Interactive: 1.0.3-beta.2+e045de2a48

### More detailed mod list:

architectury-9.2.14-fabric.jar
azurelib-fabric-1.20.1-2.0.20.jar
cardinal-components-api-5.2.2.jar
cavedweller-1.3.0.jar
chunkloaders-1.2.8a-fabric-mc1.20.1(1).jar
cloth-config-11.1.118-fabric.jar
collective-1.20.1-7.64.jar
create_dd-0.1d.jar
create_interactive-1.0.3-beta.2+e045de2a48
create-fabric-0.5.1-f-build.1417+mc1.20.1.jar
createutilities-0.3.0+1.20.1.jar
dankstorage-fabric-1.20.1-9.jar
emi-1.1.0+1.20.1+fabric.jar
eureka-1201-1.5.1-beta.3.jar
fabric-api-0.92.2+1.20.1.jar
fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar
geckolib-fabric-1.20.1-4.4.6.jar
indium-1.0.31+mc1.20.4.jar
iris-1.7.0+mc1.20.1.jar
iris-flywheel-compat-1.20.1-0.2.5.jar
Jade-1.20-fabric-11.7.0.jar
modmenu-7.2.2.jar
oreharvester-1.20.1-1.2.jar
owo-lib-0.11.2+1.20.jar
Retraining-fabric-1.20.1-1.3.1.jar
SimpleAnimatedGuns-1.20.1-v1.3-BETA-2.jar
sodium-fabric-0.5.8+mc1.20.1(1).jar
supermartijn642configlib-1.1.8a-fabric-mc1.20(1).jar
supermartijn642corelib-1.1.17-fabric-mc1.20.1.jar
TheManFromTheFog-1.1.1+fabric.mc.1.20.1.jar
travelers-backpack-1.20.1-9.1.9.jar
treeharvester-1.20.1-8.7.jar
valkyrienskies-120-2.3.0-beta.5.jar
villagerinabucket-1.20.1-1.2.0.jar
Xaeros_Minimap_23.9.7_Fabric_1.20.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
Zoomify-2.11.2.jar

**Comment by jwols123** [comment]
I do not know what is up with Create: Interactive but it's just like completely broken rn. Although I LOVE the idea of it, it breaks way too many things. For now the "fix" is just removing it.

**Comment by blockninja124** [comment]
Fixed in dev

**Comment by blockninja124** [comment]
Closing since fixed in dev
