### ISSUE TITLE
create interactive not working

### ISSUE THREAD

**Issue by ALEILGOD** [ValkyrienSkies/Create-Interactive-Issues#93]
I installed create interactive but the contraptions are normal and i cant place, destroy or do anything that create interactive does, the blocks are loaded so the mod is loaded but it wont work

[Modlist](https://github.com/user-attachments/files/16334648/Modlist.txt)

**Comment by ALEILGOD** [comment]
and i can't have the train derail well
i'm using version 1.20.1 latest

**Comment by levkirillov** [comment]
same issue

**Comment by levkirillov** [comment]
you need to place interact me block on train but it have broken texture.

**Comment by Gobamushy** [comment]
this is wack

**Comment by blockninja124** [comment]
Interact me block is needed
